/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manage_flights.java
 *
 * Created on 27 Dec, 2019, 10:34:55 PM
 */

/**
 *
 * @author Vaibhav Agarwal
 */
import javax.swing.JOptionPane;
import java.sql.*;

import java.sql.DriverManager;
public class Add_Flights extends javax.swing.JFrame {

    /** Creates new form manage_flights */
    public Add_Flights() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("STORE ON SERVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 190, 180, 50);

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 41, 23);

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 250, 170, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 255, 204));
        jLabel1.setText("ADD/SEARCH FOR FLIGHTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 332, 29);

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("F_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 200, 130, 14);

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("F_NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 220, 120, 14);

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("F_ONLINE_SERVICE_DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 240, 160, 14);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("F_OFFLINE_TIMING");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 260, 150, 14);

        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("F_TIME_NAME");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 300, 140, 14);

        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("F_FACILITIES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 280, 100, 14);

        jTextField1.setText("                 ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(330, 200, 120, 20);

        jTextField2.setText("                 ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(330, 220, 120, 20);

        jTextField3.setText("                  ");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(330, 240, 120, 20);

        jTextField4.setText("                 ");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(330, 260, 120, 20);

        jTextField6.setText("                 ");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(330, 300, 120, 20);

        jTextField7.setText("             ");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(330, 280, 120, 20);

        jLabel11.setText("HH:MM:SS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 280, 60, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/193160.jpg"))); // NOI18N
        jLabel10.setText("hh");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-930, -10, 2120, 1200);

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 280, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try
        {
      Class.forName("java.sql.Driver");
             Connection con = (Connection)
                  DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","vaibhav");

          
             String c,d,e,f,g,h,i,j;
             c=jTextField1.getText();
             d=jTextField2.getText();
             e=jTextField3.getText();
             f=jTextField4.getText();
            // g=jTextField5.getText();
             h=jTextField6.getText();
             i=jTextField7.getText();
             //j=jTextField8.getText();
             Statement stmt = null;
             stmt = con.createStatement();
             String SQL ="insert into flight_status values('"+(c)+"','"+(d)+"','"+(i)+"','"+(f)+"',null,'"+(h)+"','"+(e)+"',null);";
             int u = stmt.executeUpdate(SQL);
             JOptionPane.showMessageDialog(this,"Your Flight is Added");
             
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
      // jTextField5.setText("");
       jTextField6.setText("");
       jTextField7.setText("");
     //  jTextField8.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String id = jTextField1.getText();
        try{
              Class.forName("java.sql.Driver");
             Connection con = (Connection)
                  DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","vaibhav");
             {
             Statement stmt = null;
              ResultSet rs = null;
              stmt= con.createStatement();
             String SQL = "Select * from flight_status where f_id='"+(id)+"';";
             rs = stmt.executeQuery(SQL);
             while(rs.next()){
                 String a = rs.getString("f_id");
                 String b = rs.getString("f_name");
                 String c = rs.getString("f_onservice_date");
               //  String d = rs.getString("f_offservice_date");
             //    String e = rs.getString("f_online_timing");
                 String f = rs.getString("f_offline_timing");
                 String g = rs.getString("f_facilities");
                 String h = rs.getString("f_time_name");

                 jTextField1.setText(""+a);
                 jTextField2.setText(""+b);
                 jTextField3.setText(""+c);
               //  jTextField1.setText(""+d);
                 jTextField4.setText(""+f);
                // jTextField1.setText(""+f);
                 jTextField7.setText(""+g);
                 jTextField6.setText(""+h);
             }

              rs.close();
             stmt.close();
          }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,e.getMessage());
       }     // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   new Admin_Office().setVisible(true);

}//GEN-LAST:event_jButton2ActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
