/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login_page.java
 *
 * Created on 27 Dec, 2019, 5:08:07 PM
 */

/**
 *
 * @author Vaibhav Agarwal
 */

public class login_page extends javax.swing.JFrame {

    /** Creates new form login_page */
    public login_page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setForeground(new java.awt.Color(255, 255, 0));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTextField1.setText("                                             ");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(490, 220, 80, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 250, 0, 0);

        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(187, 340, 130, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "CUSTOMER" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 280, 110, 20);

        jPasswordField1.setText("    ");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(490, 250, 40, 20);

        jLabel4.setText("                     ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 230, 150, 14);

        jButton2.setText("not your user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 340, 140, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.PNG"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(579, 300));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 2580, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 jTextField1.setVisible(false);
     jPasswordField1.setVisible(false);
     jButton2.setVisible(false);           // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jComboBox1.getSelectedIndex()==0){
            jTextField1.setVisible(true);
            jPasswordField1.setVisible(true);
            jButton1.setText("Login");
            jComboBox1.setVisible(false);
            jButton2.setVisible(true);
            jLabel4.setText("Enter Your Information");
        }else{
           this.dispose();
            new destination_page().setVisible(true);
        }

        String usname = jTextField1.getText();
        String pas = String.valueOf(jPasswordField1.getPassword());
            if(usname.equals("Vaibhav@11")||(pas.equals("1234"))){
            new Admin_Office().setVisible(true);
            this. dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jComboBox1.setVisible(true);
        jButton2.setVisible(false);
        jLabel4.setText("Select your User Type");
        jTextField1.setVisible(false);
        jPasswordField1.setVisible(false);
        jButton1.setText("Confirm");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
